title:            Sushant Hiray's Web Space
description:      My rants on programming
url:              http://sushant-hiray.me
disqus_shortname: sushantgitblog

# Owner/author information
owner:
  name:           Sushant Hiray
  avatar:         bio-photo.jpg
  bio:            "Ahead by x-commits"
  email:          hiraysushant@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        SushantHiray
  facebook:       sushant.hiray
  github:         sushant-hiray
  google_plus:    sushanthiray


timezone:    Asia/Kolkata
future:      true
highlighter:  pygments
markdown:    redcarpet

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /posts/:categories/:title/
lsi: true
exclude: ['README.markdown', 'README_FOR_COLLABORATORS.markdown', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'LICENSE.txt']
production: false
paginate: 5

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
